### ISSUE TITLE
The generate configuration can't complete handshake

### ISSUE THREAD

**Issue by zhylmzr** [poscat0x04/wgcf-teams#2]
![屏幕截图 2023-02-18 203405](https://user-images.githubusercontent.com/15730824/219866020-68da21e7-a52c-40ce-a7ce-6cbd76436a72.png)

**Comment by poscat0x04** [comment]
Please check that the server IP (`162.159.192.1`) is reachable from your network. Also note that some cloudflare colocation checks whether the `wg.reserved` bytes in the packet they received equal to the `routing-id` of the client. If that is the case for the cloudflare colocation you had peered to then you might need to modify the packets sent by your client.

**Comment by zhylmzr** [comment]
> Also note that some cloudflare colocation checks whether the `wg.reserved` bytes in the packet they received equal to the `routing-id` of the client. 

I think this is where the problem lies.

As a supplementary explanation, the standard WireGuard client does not provide the function to modify `reserved`.
